docker-gc:
  environment:
    - EXCLUDE_CONTAINERS_FROM_GC=/exclude_containers_list
    - EXCLUDE_FROM_GC=/exclude_images_list
    - FORCE_IMAGE_REMOVAL=${FORCE_IMAGE_REMOVAL}
    - FORCE_CONTAINER_REMOVAL=${FORCE_CONTAINER_REMOVAL}
    - DRY_RUN=${DRY_RUN}
  image: chessracer/docker-docker-gc-crond:latest
  privileged: true
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  labels:
      io.rancher.scheduler.global: 'true'
  tty: true
  stdin_open: true
